# Generated by Django 4.1 on 2022-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
