# Generated by Django 4.1 on 2022-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_enterprise_tz_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='tz_info',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Europe/Moscow', 'Europe/Moscow'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg')], default='UTC', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
